### ISSUE TITLE
Compatibility to CKAN 2.7.x

### ISSUE THREAD

**Issue by goldi42** [GovDataOfficial/ckanext-dcatde#1]
Our CKAN platform will run with CKAN 2.7 and we plan to integrate our dcatde extension.
At the moment the extension only supports CKAN 2.5.2.
I removed the CKAN requirements from the requirements file and the first tests looks good with CKAN 2.7
The ckanext-dcat extension also supports CKAN 2.7

**Comment by okoroyin** [comment]
Thank you for your comment. The Extension was developed using CKAN 2.5.2 that's just that Version is supported. We would appreciate greatly if you keep us updated about your experiences with CKAN 2.7.

**Comment by volkerjaenisch** [comment]
I am supporting the findings of goldi42. Runs without flaws under 2.7.2.

**Comment by okoroyin** [comment]
@volkerjaenisch: thank you for the Info!

**Comment by knudmoeller** [comment]
@volkerjaenisch That's a relief. We (Berlin) are also using CKAN 2.7.2.

**Comment by seitenbau-govdata** [comment]
Closed, because the original question is answered. It seems that the plugin is working well with CKAN 2.7.x.

**Comment by gallexme** [comment]
#9  @seitenbau-govdata  as its compatible, removing it should be better
