### ISSUE TITLE
Rename the requirements file

### ISSUE THREAD

**Issue by goldi42** [GovDataOfficial/ckanext-dcatde#2]
At the moment the requirements are defined in `base-requirements.txt`.
It would be nice if the file has the same name like the other CKAN extensions, ckanext-dact for example.
At ckanext-dcat the file has the name `requirements.txt`

**Comment by seitenbau-govdata** [comment]
Hello @goldi42 ,
as we can see, there is no consistent naming of the requirements file in the CKAN extensions. We have adopted the naming from ckanext-harvest and using it in our other CKAN extensions in the same way. And yet some other CKAN extensions naming it pip-requirements.txt, e.g. ckanext-spatial or ckanext-geoview. Hence we see no need at the moment to rename the requirements file and we'll keep the requirements file defined as `base-requirements.txt`.
