### ISSUE TITLE
pyparsing Kompatibilität mit CKAN 2.10

### ISSUE THREAD

**Issue by jze** [GovDataOfficial/ckanext-dcatde#20]
Es scheint so, als würde diese Abhängigkeit ein Zusammenspiel mit CKAN 2.10 verhindert, da CKAN 2.10 pyparsing in Version 3.0.7 installieren möchte.

https://github.com/GovDataOfficial/ckanext-dcatde/blob/873db9a980da72859f99bb4d23c9a27c74f0424a/base-requirements.txt#L6

**Comment by thorge** [comment]
Pyparsing scheint auch an keiner Stelle importiert zu werden, es ist nur in den [base-requirements](https://github.com/GovDataOfficial/ckanext-dcatde/blob/873db9a980da72859f99bb4d23c9a27c74f0424a/base-requirements.txt#L6) gelistet.

**Comment by seitenbau-govdata** [comment]
Die Abhängigkeit wurde einst festgelegt, um ein Problem mit `rdflib 5.x` zu beheben (https://github.com/RDFLib/rdflib/issues/1204). Vermutlich wird dieser Fix gar nicht mehr benötigt und kann entfernt werden. Danke für den Hinweis, wir werden uns das nochmal genauer anschauen.
