### ISSUE TITLE
Integration with scheming

### ISSUE THREAD

**Issue by dev-rke** [GovDataOfficial/ckanext-dcatde#26]
Hi,

i would like to apply my own scheme to imported records by the dcat de harvester. 
I defined for example a new field "theme" using the scheming extension.
When harvesting a record having a dcat theme defined, it crashes with the message:
`[ckanext.harvest.model] Create validation Error: {'Extras': 'There is a schema field with the same name'}`
Creating records manually works without issues.

I also saw, some are working in the base extension on that topic, but this seems not to be ready yet.
https://github.com/ckan/ckanext-dcat/pull/281

How do you typically solve this kind of issue? 
Creating a custom profile and moving fields from extras to root level?
Can i define a scheme for an extras field manually?

Thank you.

**Comment by amercader** [comment]
@dev-rke this is exactly the kind of issue that the `euro_dcat_ap_scheming` profile in the pull request you link to is meant to help address. That is almost ready to go and will be merged soon, it would be great if you could try it out to see if there are any issues when using it in a real world scenario.

**Comment by dev-rke** [comment]
Hi @amercader ,

Thanks for your feedback.
As i am no native python developer, what is the preferred way to integrate that pull request within my docker container?
Currently we define all extensions in a requirements.txt and install them from there when building a container, e.g.
```
-e git+https://github.com/ckan/ckanext-dcat.git@v1.7.0#egg=ckanext_dcat
-e git+https://github.com/GovDataOfficial/ckanext-dcatde.git@6.8.0#egg=ckanext_dcatde
```

May i define the pr within the requirements.txt anyhow?
Or is there some patch management approach i may use?

Is it possible to define such a mapping on a per-field basis? 
E.g. using a scheming preset? Did not find any examples, some ideas or links are appreciated.
As i don't want to spam the issue here, is there some user group / forum where to ask further questions?

Thanks for a short insight. :-)

**Comment by amercader** [comment]
@dev-rke you can point to the development branch now, and to the master branch when merged:

```
-e git+https://github.com/ckan/ckanext-dcat.git@56-add-schema-file-dcat-ap-2.1#egg=ckanext_dcat
```

The pull request contains a couple of example scheming schemas with DCAT-AP fields if that's what you are asking:

* [Recommended fields](https://github.com/ckan/ckanext-dcat/pull/281/files#diff-cb88d7e03df74be2c6e0087e17a9b97232adbb145523857940f34a0b9247b36f)
* [All fields](https://github.com/ckan/ckanext-dcat/pull/281/files#diff-77ebe48c2b442fff506a3aad288a513d3f116ded7c6f1eea67143f8e1abadb27)

You don't need to define all fields in your schema, only the ones your site needs to support. The `euro_dcat_ap_scheming` profile will take care of handling only the fields defined in the schema.

Going forward you can create an issue in the [ckanext-dcat repo](https://github.com/ckan/ckanext-dcat).

**Comment by dev-rke** [comment]
@amercader  perfect answer, thx, missed that egg! :D
