### ISSUE TITLE
config.ini and ci-config.ini files inside the repository

### ISSUE THREAD

**Issue by goldi42** [GovDataOfficial/ckanext-dcatde#3]
In the extension are two files `config.ini` and `ci-config.ini`.
Are they just for your development or testing environment? Or are they loaded by default?

I ask because you change the `ckan.site_url` to `http://localhost`.

**Comment by seitenbau-govdata** [comment]
Hello @goldi42,
yes, these are configuration files only for local development and testing. To avoid misunderstandings regarding to the usage we'll merge the two files and rename it to `test.ini` with the next update, as it seems to be the standard approach in other CKAN extensions.

**Comment by seitenbau-govdata** [comment]
Fixed with https://github.com/GovDataOfficial/ckanext-dcatde/commit/026d893a9701e069075124568d64639bc0a86758
