### ISSUE TITLE
Remove IDE files from repository

### ISSUE THREAD

**Issue by goldi42** [GovDataOfficial/ckanext-dcatde#4]
At the repository are some IDE files in the repository.
Can you remove that files from the repository and add them to the gitignore

**Comment by seitenbau-govdata** [comment]
Hello @goldi42,
thanks for the hint. We'll remove the IDE files and add them to the gitignore in the next version. The upcoming update is scheduled to be published within the next few days.

**Comment by seitenbau-govdata** [comment]
Fixed with https://github.com/GovDataOfficial/ckanext-dcatde/commit/b91550fe8f7f8bbcdab8fad4dcff642b795b3801
