### ISSUE TITLE
Remove CKAN 2.5.2 Version Fixation

### ISSUE THREAD

**Issue by gallexme** [GovDataOfficial/ckanext-dcatde#9]
this Plugin is Compatible with multiple CKAN Versions,
the CKAN Version should not be enforced in https://github.com/GovDataOfficial/ckanext-dcatde/blob/master/base-requirements.txt

**Comment by seitenbau-govdata** [comment]
Thanks for your input. We will check that and we probably remove the restriction to a specific version of CKAN in the next release.

**Comment by seitenbau-govdata** [comment]
Already fixed in the repo https://github.com/GovDataOfficial/ckanext-searchindexhook by commit https://github.com/GovDataOfficial/ckanext-searchindexhook/commit/576d88f320b3335ebb9d958c049c337b4497e807

The fix in this repo will be follow soon. 😃

**Comment by seitenbau-govdata** [comment]
Fixed with commit https://github.com/GovDataOfficial/ckanext-dcatde/commit/bd29fa4f1a0836b8f3d378d30eb86f3f4d1f3659
And additionally for the repo _ckanext-govdatade_ https://github.com/GovDataOfficial/ckanext-govdatade/commit/40bb519df4af9d7f5ea647485f69a1bd8c74851f
